### ISSUE TITLE
copy-headers.cmake not found

### ISSUE THREAD

**Issue by simonlegrand** [ampl/gsl#21] opened 2017-05-05 15:35 UTC
Hello,

I had troubles to compile the GSL on my Windows 10 with Visual Studio 2015 and 2017.  Errors occured during the build step:
`Error processing file: copy-headers.cmake`
leading to
`Cannot open include file: 'gsl/gsl_*.h': No such file or directory`
because headers had not been copied in the gsl/ directory.

The solution I have found is to replace line 592 of the CMakeLists.txt:
`COMMAND ${CMAKE_COMMAND} -P copy-headers.cmake)`
by
`COMMAND ${CMAKE_COMMAND} -P ${CMAKE_CURRENT_BINARY_DIR}/copy-headers.cmake)`

Regards,

Simon

**Comment by fdabrandao** [comment] 2017-05-05 16:19
Thanks for reporting this issue and for identifying its root cause. It has been fixed in 2af85e751dd8c3a9a62e8b2b0e84d9364b086936.

**Closed** 2017-05-05 16:21 UTC
